version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependabot
      - dependencies
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependabot
      - dependencies
