plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 100

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 500

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - sig/**/*.rbs

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma